# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57716a458e630bb05a7f20f406c24d80f770a7a902f7168c068acf3e272dc44d9384edf7b97711b89d161e868e9d6876ad7f819fb9e1f1be8acf9bebe56c4c2a

test:
  secret_key_base: 076183373ead2006fd5e7a51644ef60d17cd0e4f50edd440c4385748a37152ad457b0c0bed313e7adbabe5427deeee01ae07493a021ae156727fe6c311ed6207

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
